image: node:10

# Cache modules in between jobs (caching setup copied from https://docs.gitlab.com/ee/ci/caching/index.html)
# Use specific job cache settings to allow 1 setup job to push, and all other jobs to pull
#cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    paths:
#        - node_modules/

.job_template: &std_job
    cache: &pull_module_cache
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - node_modules/
    only: &only_constraints
        - merge_requests
        - /^(fix|feature|meta)/
        - tags


stages:
    - setup
    - test
    - deploy

before_script:
    # setting unsafe-perm and shell config is needed to get the mattermost-redux
    # dependency correctly installed BECAUSE it is a git url w/ a prepare script
    # AND the node image user is root! npm acts differently when run as root!
    - npm config set unsafe-perm true
    - npm config set shell /bin/bash

npm-install:
    stage: setup
    script:
        - npm install
    only: *only_constraints
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules/

check-style:
    <<: *std_job
    stage: test
    script:
        - make check-style-ci THRESHOLD=50
    artifacts:
        when: always
        paths:
            - build/check-style.log.html

test:
    <<: *std_job
    stage: test
    script:
        - make test-ci
        - tail --lines=14 build/test.log
    artifacts:
        when: always
        paths:
            - build/test.log
            - build/test-results.xml

build:
    <<: *std_job
    stage: test     # test rather than build, as it doesn't need to complete before testing
    script:
        - make build > build/build.log
    artifacts:
        when: always
        paths:
            - build/build.log
